# Generated by Django 2.2.12 on 2023-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViT_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=1024)),
                ('Route', models.CharField(max_length=128)),
                ('Classes', models.IntegerField(default=0)),
            ],
        ),
    ]
